eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
server:
  port: 8999
  
spring:      
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:      
      - id: CUSTOMER-SERICE
        predicates:
        - Path=/api/customer/**
        uri: lb://CUSTOMER-SERICE
        
      - id: FIXED-DEPOSIT-SERVICE
        predicates:
        - Path= /api/fixed-deposits/**
        uri: lb://api/fixed-deposits
        
      - id: INTEREST-RATE-SERVICE
        predicates:
        - Path= /api/interest-rates/**
        uri: lb://api/interest-rates
        
      - id: NOTIFICATION-SERVICE
        predicates:
        - Path= /api/notifications/**
        uri: lb://api/notifications


        
